#!/bin/sh
iptables-restore <<EOF
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state ESTABLISHED -j ACCEPT
COMMIT
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:FSM_PROXY_INBOUND - [0:0]
:FSM_PROXY_IN_REDIRECT - [0:0]
:FSM_PROXY_OUTBOUND - [0:0]
:FSM_PROXY_OUT_REDIRECT - [0:0]
-A PREROUTING -p tcp -j FSM_PROXY_INBOUND
-A OUTPUT -p tcp -j FSM_PROXY_OUTBOUND
-A FSM_PROXY_INBOUND -p tcp -m multiport --dports 22 -j RETURN
-A FSM_PROXY_INBOUND -p tcp -m tcp --dport 15010 -j RETURN
-A FSM_PROXY_INBOUND -p tcp -m tcp --dport 15901 -j RETURN
-A FSM_PROXY_INBOUND -p tcp -m tcp --dport 15902 -j RETURN
-A FSM_PROXY_INBOUND -p tcp -m tcp --dport 15903 -j RETURN
-A FSM_PROXY_INBOUND -p tcp -m tcp --dport 15904 -j RETURN
-A FSM_PROXY_INBOUND -p tcp -j FSM_PROXY_IN_REDIRECT
-A FSM_PROXY_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15003
-A FSM_PROXY_OUTBOUND ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1500 -j FSM_PROXY_IN_REDIRECT
-A FSM_PROXY_OUTBOUND -o lo -m owner ! --uid-owner 1500 -j RETURN
-A FSM_PROXY_OUTBOUND -m owner --uid-owner 1500 -j RETURN
-A FSM_PROXY_OUTBOUND -d 127.0.0.1/32 -j RETURN
-A FSM_PROXY_OUTBOUND -p tcp -m multiport --dports 853 -j RETURN
-A FSM_PROXY_OUTBOUND -j FSM_PROXY_OUT_REDIRECT
-A FSM_PROXY_OUT_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A FSM_PROXY_OUT_REDIRECT -p tcp -m tcp --dport 15000 -j ACCEPT
COMMIT
EOF
